{% set name = "sortedcontainers-pydantic" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sortedcontainers_pydantic-{{ version }}.tar.gz
  sha256: eb0e4aeb5197d690165f0a7b1a55c490eabe4b21375c3a91726373b2551e25ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - pydantic >=2
    - pydantic-core
    - sortedcontainers

test:
  imports:
    - sortedcontainers_pydantic
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Pydantic support for the sortedcontainers package.
  license: MIT
  license_file: LICENSE
  home: https://github.com/drivendataorg/sortedcontainers-pydantic

extra:
  recipe-maintainers:
    - jayqi
